function createfigure(X1, Y1, X2, Y2)
%CREATEFIGURE(X1, Y1, X2, YMatrix1)
%  X1:  vector of plot x data
%  Y1:  vector of plot y data
%  X2:  vector of plot x data
%  Y2:  vector of plot y data
%  Auto-generated by MATLAB on 04-Jun-2022 13:10:19

% Create figure
 figure1 = figure('WindowState','normal');

% Create axes
axes1 = axes('Parent',figure1);
hold(axes1,'on');
% hold on
% Create plot
plot(X1,Y1,'DisplayName','Meas.','LineWidth',1,...
    'Color',[0.501960784313725 0.501960784313725 0.501960784313725]); % Meas.' [0 0 1] '1D Smith 81 (\lambda/2=1500 nm)'

% Create multiple line objects using matrix input to plot
 plot(X2,Y2,'LineWidth',1.3,'DisplayName','1D (\lambda/2=1400 nm)','Color',[0 0 1]);
% set(plot1,'DisplayName','2D FEM (\lambda=1400 \mum)','Color',[0 0 1]);
% set(plot1(2),'DisplayName','3D FEM (\lambda=1400 \mum)','Color',[1 0 0]);
% plot(X3,Y3,'LineWidth',1.6,'DisplayName','2D (\lambda/2=1400 nm)','Color',[0 0 1]);
% plot(X4,Y4,'LineWidth',1.6,'DisplayName','3D (\lambda/2=1400 nm)','Color',[1 0 0]);
% Create ylabel
ylabel('Electrical Impedance (dB\Omega)','FontName','Times New Roman');

% Create xlabel
xlabel('Frequency(MHz)','FontName','Times New Roman');

% Create title
% title('Basic Cell','FontName','Times New Roman');

% Uncomment the following line to preserve the X-limits of the axes
xlim(axes1,[1100 1800]);
% Uncomment the following line to preserve the Y-limits of the axes
ylim(axes1,[10 80]);
grid(axes1,'on');
hold(axes1,'off');
% Set the remaining axes properties
set(axes1,'FontName','Times New Roman','FontSize',13,'XTick',...
    (1000:100:1800),'YTick',(-10:10:110));
% Create legend
legend1 = legend(axes1,'show');
set(legend1,'Location','southeast','FontName','Times');

